# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyclblas', [dirname(__file__)])
        except ImportError:
            import _pyclblas
            return _pyclblas
        if fp is not None:
            try:
                _mod = imp.load_module('_pyclblas', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyclblas = swig_import_helper()
    del swig_import_helper
else:
    import _pyclblas
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


clblasRowMajor = _pyclblas.clblasRowMajor
clblasColumnMajor = _pyclblas.clblasColumnMajor
clblasNoTrans = _pyclblas.clblasNoTrans
clblasTrans = _pyclblas.clblasTrans
clblasConjTrans = _pyclblas.clblasConjTrans
clblasUpper = _pyclblas.clblasUpper
clblasLower = _pyclblas.clblasLower
clblasUnit = _pyclblas.clblasUnit
clblasNonUnit = _pyclblas.clblasNonUnit
clblasLeft = _pyclblas.clblasLeft
clblasRight = _pyclblas.clblasRight
clblasSuccess = _pyclblas.clblasSuccess
clblasInvalidValue = _pyclblas.clblasInvalidValue
clblasInvalidCommandQueue = _pyclblas.clblasInvalidCommandQueue
clblasInvalidContext = _pyclblas.clblasInvalidContext
clblasInvalidMemObject = _pyclblas.clblasInvalidMemObject
clblasInvalidDevice = _pyclblas.clblasInvalidDevice
clblasInvalidEventWaitList = _pyclblas.clblasInvalidEventWaitList
clblasOutOfResources = _pyclblas.clblasOutOfResources
clblasOutOfHostMemory = _pyclblas.clblasOutOfHostMemory
clblasInvalidOperation = _pyclblas.clblasInvalidOperation
clblasCompilerNotAvailable = _pyclblas.clblasCompilerNotAvailable
clblasBuildProgramFailure = _pyclblas.clblasBuildProgramFailure
clblasNotImplemented = _pyclblas.clblasNotImplemented
clblasNotInitialized = _pyclblas.clblasNotInitialized
clblasInvalidMatA = _pyclblas.clblasInvalidMatA
clblasInvalidMatB = _pyclblas.clblasInvalidMatB
clblasInvalidMatC = _pyclblas.clblasInvalidMatC
clblasInvalidVecX = _pyclblas.clblasInvalidVecX
clblasInvalidVecY = _pyclblas.clblasInvalidVecY
clblasInvalidDim = _pyclblas.clblasInvalidDim
clblasInvalidLeadDimA = _pyclblas.clblasInvalidLeadDimA
clblasInvalidLeadDimB = _pyclblas.clblasInvalidLeadDimB
clblasInvalidLeadDimC = _pyclblas.clblasInvalidLeadDimC
clblasInvalidIncX = _pyclblas.clblasInvalidIncX
clblasInvalidIncY = _pyclblas.clblasInvalidIncY
clblasInsufficientMemMatA = _pyclblas.clblasInsufficientMemMatA
clblasInsufficientMemMatB = _pyclblas.clblasInsufficientMemMatB
clblasInsufficientMemMatC = _pyclblas.clblasInsufficientMemMatC
clblasInsufficientMemVecX = _pyclblas.clblasInsufficientMemVecX
clblasInsufficientMemVecY = _pyclblas.clblasInsufficientMemVecY

def clblasGetVersion(*args):
  return _pyclblas.clblasGetVersion(*args)
clblasGetVersion = _pyclblas.clblasGetVersion

def clblasSetup():
  return _pyclblas.clblasSetup()
clblasSetup = _pyclblas.clblasSetup

def clblasTeardown():
  return _pyclblas.clblasTeardown()
clblasTeardown = _pyclblas.clblasTeardown

def clblasSswap(*args):
  return _pyclblas.clblasSswap(*args)
clblasSswap = _pyclblas.clblasSswap

def clblasDswap(*args):
  return _pyclblas.clblasDswap(*args)
clblasDswap = _pyclblas.clblasDswap

def clblasCswap(*args):
  return _pyclblas.clblasCswap(*args)
clblasCswap = _pyclblas.clblasCswap

def clblasZswap(*args):
  return _pyclblas.clblasZswap(*args)
clblasZswap = _pyclblas.clblasZswap

def clblasSscal(*args):
  return _pyclblas.clblasSscal(*args)
clblasSscal = _pyclblas.clblasSscal

def clblasDscal(*args):
  return _pyclblas.clblasDscal(*args)
clblasDscal = _pyclblas.clblasDscal

def clblasCscal(*args):
  return _pyclblas.clblasCscal(*args)
clblasCscal = _pyclblas.clblasCscal

def clblasZscal(*args):
  return _pyclblas.clblasZscal(*args)
clblasZscal = _pyclblas.clblasZscal

def clblasCsscal(*args):
  return _pyclblas.clblasCsscal(*args)
clblasCsscal = _pyclblas.clblasCsscal

def clblasZdscal(*args):
  return _pyclblas.clblasZdscal(*args)
clblasZdscal = _pyclblas.clblasZdscal

def clblasScopy(*args):
  return _pyclblas.clblasScopy(*args)
clblasScopy = _pyclblas.clblasScopy

def clblasDcopy(*args):
  return _pyclblas.clblasDcopy(*args)
clblasDcopy = _pyclblas.clblasDcopy

def clblasCcopy(*args):
  return _pyclblas.clblasCcopy(*args)
clblasCcopy = _pyclblas.clblasCcopy

def clblasZcopy(*args):
  return _pyclblas.clblasZcopy(*args)
clblasZcopy = _pyclblas.clblasZcopy

def clblasSaxpy(*args):
  return _pyclblas.clblasSaxpy(*args)
clblasSaxpy = _pyclblas.clblasSaxpy

def clblasDaxpy(*args):
  return _pyclblas.clblasDaxpy(*args)
clblasDaxpy = _pyclblas.clblasDaxpy

def clblasCaxpy(*args):
  return _pyclblas.clblasCaxpy(*args)
clblasCaxpy = _pyclblas.clblasCaxpy

def clblasZaxpy(*args):
  return _pyclblas.clblasZaxpy(*args)
clblasZaxpy = _pyclblas.clblasZaxpy

def clblasSdot(*args):
  return _pyclblas.clblasSdot(*args)
clblasSdot = _pyclblas.clblasSdot

def clblasDdot(*args):
  return _pyclblas.clblasDdot(*args)
clblasDdot = _pyclblas.clblasDdot

def clblasCdotu(*args):
  return _pyclblas.clblasCdotu(*args)
clblasCdotu = _pyclblas.clblasCdotu

def clblasZdotu(*args):
  return _pyclblas.clblasZdotu(*args)
clblasZdotu = _pyclblas.clblasZdotu

def clblasCdotc(*args):
  return _pyclblas.clblasCdotc(*args)
clblasCdotc = _pyclblas.clblasCdotc

def clblasZdotc(*args):
  return _pyclblas.clblasZdotc(*args)
clblasZdotc = _pyclblas.clblasZdotc

def clblasSrotg(*args):
  return _pyclblas.clblasSrotg(*args)
clblasSrotg = _pyclblas.clblasSrotg

def clblasDrotg(*args):
  return _pyclblas.clblasDrotg(*args)
clblasDrotg = _pyclblas.clblasDrotg

def clblasCrotg(*args):
  return _pyclblas.clblasCrotg(*args)
clblasCrotg = _pyclblas.clblasCrotg

def clblasZrotg(*args):
  return _pyclblas.clblasZrotg(*args)
clblasZrotg = _pyclblas.clblasZrotg

def clblasSrotmg(*args):
  return _pyclblas.clblasSrotmg(*args)
clblasSrotmg = _pyclblas.clblasSrotmg

def clblasDrotmg(*args):
  return _pyclblas.clblasDrotmg(*args)
clblasDrotmg = _pyclblas.clblasDrotmg

def clblasSrot(*args):
  return _pyclblas.clblasSrot(*args)
clblasSrot = _pyclblas.clblasSrot

def clblasDrot(*args):
  return _pyclblas.clblasDrot(*args)
clblasDrot = _pyclblas.clblasDrot

def clblasCsrot(*args):
  return _pyclblas.clblasCsrot(*args)
clblasCsrot = _pyclblas.clblasCsrot

def clblasZdrot(*args):
  return _pyclblas.clblasZdrot(*args)
clblasZdrot = _pyclblas.clblasZdrot

def clblasSrotm(*args):
  return _pyclblas.clblasSrotm(*args)
clblasSrotm = _pyclblas.clblasSrotm

def clblasDrotm(*args):
  return _pyclblas.clblasDrotm(*args)
clblasDrotm = _pyclblas.clblasDrotm

def clblasSnrm2(*args):
  return _pyclblas.clblasSnrm2(*args)
clblasSnrm2 = _pyclblas.clblasSnrm2

def clblasDnrm2(*args):
  return _pyclblas.clblasDnrm2(*args)
clblasDnrm2 = _pyclblas.clblasDnrm2

def clblasScnrm2(*args):
  return _pyclblas.clblasScnrm2(*args)
clblasScnrm2 = _pyclblas.clblasScnrm2

def clblasDznrm2(*args):
  return _pyclblas.clblasDznrm2(*args)
clblasDznrm2 = _pyclblas.clblasDznrm2

def clblasiSamax(*args):
  return _pyclblas.clblasiSamax(*args)
clblasiSamax = _pyclblas.clblasiSamax

def clblasiDamax(*args):
  return _pyclblas.clblasiDamax(*args)
clblasiDamax = _pyclblas.clblasiDamax

def clblasiCamax(*args):
  return _pyclblas.clblasiCamax(*args)
clblasiCamax = _pyclblas.clblasiCamax

def clblasiZamax(*args):
  return _pyclblas.clblasiZamax(*args)
clblasiZamax = _pyclblas.clblasiZamax

def clblasSasum(*args):
  return _pyclblas.clblasSasum(*args)
clblasSasum = _pyclblas.clblasSasum

def clblasDasum(*args):
  return _pyclblas.clblasDasum(*args)
clblasDasum = _pyclblas.clblasDasum

def clblasScasum(*args):
  return _pyclblas.clblasScasum(*args)
clblasScasum = _pyclblas.clblasScasum

def clblasDzasum(*args):
  return _pyclblas.clblasDzasum(*args)
clblasDzasum = _pyclblas.clblasDzasum

def clblasSgemv(*args):
  return _pyclblas.clblasSgemv(*args)
clblasSgemv = _pyclblas.clblasSgemv

def clblasDgemv(*args):
  return _pyclblas.clblasDgemv(*args)
clblasDgemv = _pyclblas.clblasDgemv

def clblasCgemv(*args):
  return _pyclblas.clblasCgemv(*args)
clblasCgemv = _pyclblas.clblasCgemv

def clblasZgemv(*args):
  return _pyclblas.clblasZgemv(*args)
clblasZgemv = _pyclblas.clblasZgemv

def clblasSsymv(*args):
  return _pyclblas.clblasSsymv(*args)
clblasSsymv = _pyclblas.clblasSsymv

def clblasDsymv(*args):
  return _pyclblas.clblasDsymv(*args)
clblasDsymv = _pyclblas.clblasDsymv

def clblasChemv(*args):
  return _pyclblas.clblasChemv(*args)
clblasChemv = _pyclblas.clblasChemv

def clblasZhemv(*args):
  return _pyclblas.clblasZhemv(*args)
clblasZhemv = _pyclblas.clblasZhemv

def clblasStrmv(*args):
  return _pyclblas.clblasStrmv(*args)
clblasStrmv = _pyclblas.clblasStrmv

def clblasDtrmv(*args):
  return _pyclblas.clblasDtrmv(*args)
clblasDtrmv = _pyclblas.clblasDtrmv

def clblasCtrmv(*args):
  return _pyclblas.clblasCtrmv(*args)
clblasCtrmv = _pyclblas.clblasCtrmv

def clblasZtrmv(*args):
  return _pyclblas.clblasZtrmv(*args)
clblasZtrmv = _pyclblas.clblasZtrmv

def clblasStrsv(*args):
  return _pyclblas.clblasStrsv(*args)
clblasStrsv = _pyclblas.clblasStrsv

def clblasDtrsv(*args):
  return _pyclblas.clblasDtrsv(*args)
clblasDtrsv = _pyclblas.clblasDtrsv

def clblasCtrsv(*args):
  return _pyclblas.clblasCtrsv(*args)
clblasCtrsv = _pyclblas.clblasCtrsv

def clblasZtrsv(*args):
  return _pyclblas.clblasZtrsv(*args)
clblasZtrsv = _pyclblas.clblasZtrsv

def clblasSger(*args):
  return _pyclblas.clblasSger(*args)
clblasSger = _pyclblas.clblasSger

def clblasDger(*args):
  return _pyclblas.clblasDger(*args)
clblasDger = _pyclblas.clblasDger

def clblasCgeru(*args):
  return _pyclblas.clblasCgeru(*args)
clblasCgeru = _pyclblas.clblasCgeru

def clblasZgeru(*args):
  return _pyclblas.clblasZgeru(*args)
clblasZgeru = _pyclblas.clblasZgeru

def clblasCgerc(*args):
  return _pyclblas.clblasCgerc(*args)
clblasCgerc = _pyclblas.clblasCgerc

def clblasZgerc(*args):
  return _pyclblas.clblasZgerc(*args)
clblasZgerc = _pyclblas.clblasZgerc

def clblasSsyr(*args):
  return _pyclblas.clblasSsyr(*args)
clblasSsyr = _pyclblas.clblasSsyr

def clblasDsyr(*args):
  return _pyclblas.clblasDsyr(*args)
clblasDsyr = _pyclblas.clblasDsyr

def clblasCher(*args):
  return _pyclblas.clblasCher(*args)
clblasCher = _pyclblas.clblasCher

def clblasZher(*args):
  return _pyclblas.clblasZher(*args)
clblasZher = _pyclblas.clblasZher

def clblasSsyr2(*args):
  return _pyclblas.clblasSsyr2(*args)
clblasSsyr2 = _pyclblas.clblasSsyr2

def clblasDsyr2(*args):
  return _pyclblas.clblasDsyr2(*args)
clblasDsyr2 = _pyclblas.clblasDsyr2

def clblasCher2(*args):
  return _pyclblas.clblasCher2(*args)
clblasCher2 = _pyclblas.clblasCher2

def clblasZher2(*args):
  return _pyclblas.clblasZher2(*args)
clblasZher2 = _pyclblas.clblasZher2

def clblasStpmv(*args):
  return _pyclblas.clblasStpmv(*args)
clblasStpmv = _pyclblas.clblasStpmv

def clblasDtpmv(*args):
  return _pyclblas.clblasDtpmv(*args)
clblasDtpmv = _pyclblas.clblasDtpmv

def clblasCtpmv(*args):
  return _pyclblas.clblasCtpmv(*args)
clblasCtpmv = _pyclblas.clblasCtpmv

def clblasZtpmv(*args):
  return _pyclblas.clblasZtpmv(*args)
clblasZtpmv = _pyclblas.clblasZtpmv

def clblasStpsv(*args):
  return _pyclblas.clblasStpsv(*args)
clblasStpsv = _pyclblas.clblasStpsv

def clblasDtpsv(*args):
  return _pyclblas.clblasDtpsv(*args)
clblasDtpsv = _pyclblas.clblasDtpsv

def clblasCtpsv(*args):
  return _pyclblas.clblasCtpsv(*args)
clblasCtpsv = _pyclblas.clblasCtpsv

def clblasZtpsv(*args):
  return _pyclblas.clblasZtpsv(*args)
clblasZtpsv = _pyclblas.clblasZtpsv

def clblasSspmv(*args):
  return _pyclblas.clblasSspmv(*args)
clblasSspmv = _pyclblas.clblasSspmv

def clblasDspmv(*args):
  return _pyclblas.clblasDspmv(*args)
clblasDspmv = _pyclblas.clblasDspmv

def clblasChpmv(*args):
  return _pyclblas.clblasChpmv(*args)
clblasChpmv = _pyclblas.clblasChpmv

def clblasZhpmv(*args):
  return _pyclblas.clblasZhpmv(*args)
clblasZhpmv = _pyclblas.clblasZhpmv

def clblasSspr(*args):
  return _pyclblas.clblasSspr(*args)
clblasSspr = _pyclblas.clblasSspr

def clblasDspr(*args):
  return _pyclblas.clblasDspr(*args)
clblasDspr = _pyclblas.clblasDspr

def clblasChpr(*args):
  return _pyclblas.clblasChpr(*args)
clblasChpr = _pyclblas.clblasChpr

def clblasZhpr(*args):
  return _pyclblas.clblasZhpr(*args)
clblasZhpr = _pyclblas.clblasZhpr

def clblasSspr2(*args):
  return _pyclblas.clblasSspr2(*args)
clblasSspr2 = _pyclblas.clblasSspr2

def clblasDspr2(*args):
  return _pyclblas.clblasDspr2(*args)
clblasDspr2 = _pyclblas.clblasDspr2

def clblasChpr2(*args):
  return _pyclblas.clblasChpr2(*args)
clblasChpr2 = _pyclblas.clblasChpr2

def clblasZhpr2(*args):
  return _pyclblas.clblasZhpr2(*args)
clblasZhpr2 = _pyclblas.clblasZhpr2

def clblasSgbmv(*args):
  return _pyclblas.clblasSgbmv(*args)
clblasSgbmv = _pyclblas.clblasSgbmv

def clblasDgbmv(*args):
  return _pyclblas.clblasDgbmv(*args)
clblasDgbmv = _pyclblas.clblasDgbmv

def clblasCgbmv(*args):
  return _pyclblas.clblasCgbmv(*args)
clblasCgbmv = _pyclblas.clblasCgbmv

def clblasZgbmv(*args):
  return _pyclblas.clblasZgbmv(*args)
clblasZgbmv = _pyclblas.clblasZgbmv

def clblasStbmv(*args):
  return _pyclblas.clblasStbmv(*args)
clblasStbmv = _pyclblas.clblasStbmv

def clblasDtbmv(*args):
  return _pyclblas.clblasDtbmv(*args)
clblasDtbmv = _pyclblas.clblasDtbmv

def clblasCtbmv(*args):
  return _pyclblas.clblasCtbmv(*args)
clblasCtbmv = _pyclblas.clblasCtbmv

def clblasZtbmv(*args):
  return _pyclblas.clblasZtbmv(*args)
clblasZtbmv = _pyclblas.clblasZtbmv

def clblasSsbmv(*args):
  return _pyclblas.clblasSsbmv(*args)
clblasSsbmv = _pyclblas.clblasSsbmv

def clblasDsbmv(*args):
  return _pyclblas.clblasDsbmv(*args)
clblasDsbmv = _pyclblas.clblasDsbmv

def clblasChbmv(*args):
  return _pyclblas.clblasChbmv(*args)
clblasChbmv = _pyclblas.clblasChbmv

def clblasZhbmv(*args):
  return _pyclblas.clblasZhbmv(*args)
clblasZhbmv = _pyclblas.clblasZhbmv

def clblasStbsv(*args):
  return _pyclblas.clblasStbsv(*args)
clblasStbsv = _pyclblas.clblasStbsv

def clblasDtbsv(*args):
  return _pyclblas.clblasDtbsv(*args)
clblasDtbsv = _pyclblas.clblasDtbsv

def clblasCtbsv(*args):
  return _pyclblas.clblasCtbsv(*args)
clblasCtbsv = _pyclblas.clblasCtbsv

def clblasZtbsv(*args):
  return _pyclblas.clblasZtbsv(*args)
clblasZtbsv = _pyclblas.clblasZtbsv

def clblasSgemm(*args):
  return _pyclblas.clblasSgemm(*args)
clblasSgemm = _pyclblas.clblasSgemm

def clblasDgemm(*args):
  return _pyclblas.clblasDgemm(*args)
clblasDgemm = _pyclblas.clblasDgemm

def clblasCgemm(*args):
  return _pyclblas.clblasCgemm(*args)
clblasCgemm = _pyclblas.clblasCgemm

def clblasZgemm(*args):
  return _pyclblas.clblasZgemm(*args)
clblasZgemm = _pyclblas.clblasZgemm

def clblasStrmm(*args):
  return _pyclblas.clblasStrmm(*args)
clblasStrmm = _pyclblas.clblasStrmm

def clblasDtrmm(*args):
  return _pyclblas.clblasDtrmm(*args)
clblasDtrmm = _pyclblas.clblasDtrmm

def clblasCtrmm(*args):
  return _pyclblas.clblasCtrmm(*args)
clblasCtrmm = _pyclblas.clblasCtrmm

def clblasZtrmm(*args):
  return _pyclblas.clblasZtrmm(*args)
clblasZtrmm = _pyclblas.clblasZtrmm

def clblasStrsm(*args):
  return _pyclblas.clblasStrsm(*args)
clblasStrsm = _pyclblas.clblasStrsm

def clblasDtrsm(*args):
  return _pyclblas.clblasDtrsm(*args)
clblasDtrsm = _pyclblas.clblasDtrsm

def clblasCtrsm(*args):
  return _pyclblas.clblasCtrsm(*args)
clblasCtrsm = _pyclblas.clblasCtrsm

def clblasZtrsm(*args):
  return _pyclblas.clblasZtrsm(*args)
clblasZtrsm = _pyclblas.clblasZtrsm

def clblasSsyrk(*args):
  return _pyclblas.clblasSsyrk(*args)
clblasSsyrk = _pyclblas.clblasSsyrk

def clblasDsyrk(*args):
  return _pyclblas.clblasDsyrk(*args)
clblasDsyrk = _pyclblas.clblasDsyrk

def clblasCsyrk(*args):
  return _pyclblas.clblasCsyrk(*args)
clblasCsyrk = _pyclblas.clblasCsyrk

def clblasZsyrk(*args):
  return _pyclblas.clblasZsyrk(*args)
clblasZsyrk = _pyclblas.clblasZsyrk

def clblasSsyr2k(*args):
  return _pyclblas.clblasSsyr2k(*args)
clblasSsyr2k = _pyclblas.clblasSsyr2k

def clblasDsyr2k(*args):
  return _pyclblas.clblasDsyr2k(*args)
clblasDsyr2k = _pyclblas.clblasDsyr2k

def clblasCsyr2k(*args):
  return _pyclblas.clblasCsyr2k(*args)
clblasCsyr2k = _pyclblas.clblasCsyr2k

def clblasZsyr2k(*args):
  return _pyclblas.clblasZsyr2k(*args)
clblasZsyr2k = _pyclblas.clblasZsyr2k

def clblasSsymm(*args):
  return _pyclblas.clblasSsymm(*args)
clblasSsymm = _pyclblas.clblasSsymm

def clblasDsymm(*args):
  return _pyclblas.clblasDsymm(*args)
clblasDsymm = _pyclblas.clblasDsymm

def clblasCsymm(*args):
  return _pyclblas.clblasCsymm(*args)
clblasCsymm = _pyclblas.clblasCsymm

def clblasZsymm(*args):
  return _pyclblas.clblasZsymm(*args)
clblasZsymm = _pyclblas.clblasZsymm

def clblasChemm(*args):
  return _pyclblas.clblasChemm(*args)
clblasChemm = _pyclblas.clblasChemm

def clblasZhemm(*args):
  return _pyclblas.clblasZhemm(*args)
clblasZhemm = _pyclblas.clblasZhemm

def clblasCherk(*args):
  return _pyclblas.clblasCherk(*args)
clblasCherk = _pyclblas.clblasCherk

def clblasZherk(*args):
  return _pyclblas.clblasZherk(*args)
clblasZherk = _pyclblas.clblasZherk

def clblasCher2k(*args):
  return _pyclblas.clblasCher2k(*args)
clblasCher2k = _pyclblas.clblasCher2k

def clblasZher2k(*args):
  return _pyclblas.clblasZher2k(*args)
clblasZher2k = _pyclblas.clblasZher2k

def clblasMatrixSizeInfo(*args):
  return _pyclblas.clblasMatrixSizeInfo(*args)
clblasMatrixSizeInfo = _pyclblas.clblasMatrixSizeInfo

def clblasCreateMatrix(*args):
  return _pyclblas.clblasCreateMatrix(*args)
clblasCreateMatrix = _pyclblas.clblasCreateMatrix

def clblasCreateMatrixWithLd(*args):
  return _pyclblas.clblasCreateMatrixWithLd(*args)
clblasCreateMatrixWithLd = _pyclblas.clblasCreateMatrixWithLd

def clblasCreateMatrixFromHost(*args):
  return _pyclblas.clblasCreateMatrixFromHost(*args)
clblasCreateMatrixFromHost = _pyclblas.clblasCreateMatrixFromHost

def clblasWriteSubMatrix(*args):
  return _pyclblas.clblasWriteSubMatrix(*args)
clblasWriteSubMatrix = _pyclblas.clblasWriteSubMatrix

def clblasWriteSubMatrixAsync(*args):
  return _pyclblas.clblasWriteSubMatrixAsync(*args)
clblasWriteSubMatrixAsync = _pyclblas.clblasWriteSubMatrixAsync

def clblasReadSubMatrix(*args):
  return _pyclblas.clblasReadSubMatrix(*args)
clblasReadSubMatrix = _pyclblas.clblasReadSubMatrix

def clblasReadSubMatrixAsync(*args):
  return _pyclblas.clblasReadSubMatrixAsync(*args)
clblasReadSubMatrixAsync = _pyclblas.clblasReadSubMatrixAsync

def clblasCopySubMatrix(*args):
  return _pyclblas.clblasCopySubMatrix(*args)
clblasCopySubMatrix = _pyclblas.clblasCopySubMatrix

def clblasCopySubMatrixAsync(*args):
  return _pyclblas.clblasCopySubMatrixAsync(*args)
clblasCopySubMatrixAsync = _pyclblas.clblasCopySubMatrixAsync

def clblasWriteVector(*args):
  return _pyclblas.clblasWriteVector(*args)
clblasWriteVector = _pyclblas.clblasWriteVector

def clblasWriteVectorAsync(*args):
  return _pyclblas.clblasWriteVectorAsync(*args)
clblasWriteVectorAsync = _pyclblas.clblasWriteVectorAsync

def clblasReadVector(*args):
  return _pyclblas.clblasReadVector(*args)
clblasReadVector = _pyclblas.clblasReadVector

def clblasReadVectorAsync(*args):
  return _pyclblas.clblasReadVectorAsync(*args)
clblasReadVectorAsync = _pyclblas.clblasReadVectorAsync

def clblasCopyVector(*args):
  return _pyclblas.clblasCopyVector(*args)
clblasCopyVector = _pyclblas.clblasCopyVector

def clblasCopyVectorAsync(*args):
  return _pyclblas.clblasCopyVectorAsync(*args)
clblasCopyVectorAsync = _pyclblas.clblasCopyVectorAsync

def clblasWriteMatrix(*args):
  return _pyclblas.clblasWriteMatrix(*args)
clblasWriteMatrix = _pyclblas.clblasWriteMatrix

def clblasWriteMatrixAsync(*args):
  return _pyclblas.clblasWriteMatrixAsync(*args)
clblasWriteMatrixAsync = _pyclblas.clblasWriteMatrixAsync

def clblasReadMatrix(*args):
  return _pyclblas.clblasReadMatrix(*args)
clblasReadMatrix = _pyclblas.clblasReadMatrix

def clblasReadMatrixAsync(*args):
  return _pyclblas.clblasReadMatrixAsync(*args)
clblasReadMatrixAsync = _pyclblas.clblasReadMatrixAsync

def clblasCopyMatrix(*args):
  return _pyclblas.clblasCopyMatrix(*args)
clblasCopyMatrix = _pyclblas.clblasCopyMatrix

def clblasCopyMatrixAsync(*args):
  return _pyclblas.clblasCopyMatrixAsync(*args)
clblasCopyMatrixAsync = _pyclblas.clblasCopyMatrixAsync

def clblasFillVector(*args):
  return _pyclblas.clblasFillVector(*args)
clblasFillVector = _pyclblas.clblasFillVector

def clblasFillVectorAsync(*args):
  return _pyclblas.clblasFillVectorAsync(*args)
clblasFillVectorAsync = _pyclblas.clblasFillVectorAsync

def clblasFillMatrix(*args):
  return _pyclblas.clblasFillMatrix(*args)
clblasFillMatrix = _pyclblas.clblasFillMatrix

def clblasFillSubMatrix(*args):
  return _pyclblas.clblasFillSubMatrix(*args)
clblasFillSubMatrix = _pyclblas.clblasFillSubMatrix

def clblasFillSubMatrixAsync(*args):
  return _pyclblas.clblasFillSubMatrixAsync(*args)
clblasFillSubMatrixAsync = _pyclblas.clblasFillSubMatrixAsync
# This file is compatible with both classic and new-style classes.


